### ndarray

In [1]:
import numpy as np

#### ndarray的基本属性

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]]) #创建一个二维数组
print(a)
print(a.ndim) #维度
print(a.shape) #形状
print(a.size) #元素个数
print(a.dtype) #数据类型
print(a.itemsize) #每个元素字节数大小

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64
8


#### ndarray的创建方式

使用array(l:list)得到ndarray，得到是一份copy

In [3]:
data = [1,2,3]
print(f"元数据地址为:{id(data)}")
arr = np.array(data)
print(f"arr1地址为:{id(arr)}")
print(f"数组数据为:{arr}")

元数据地址为:135698822441984
arr1地址为:135699094369264
数组数据为:[1 2 3]


如果是asarray，入参为list，也是copy，入参为ndarray，则不会拷贝

In [4]:
arr = np.asarray(data)
print(arr)
print(id(arr))

[1 2 3]
135698821271632


In [5]:
arr_ = np.asarray(arr)
print(arr_)
print(id(arr_))

[1 2 3]
135698821271632


 zeros()、ones()、empty()与zeros_like()、ones_like()、empty_like()

 zeros()：返回给定形状和类型的新数组，用0填充。
ones()：返回给定形状和类型的新数组，用1填充。
empty()：返回给定形状和类型的未初始化的新数组。
需要注意的是，np.empty并不保证数组元素被初始化为0，它只是分配内存空间，数组
中的元素值是未初始化的，可能是内存中的任意值。
上述3个方法创建的数组元素类型默认都是float64。

zeros_like()：返回与给定数组具有相同形状和类型的0新数组。
ones_like()：返回与给定数组具有相同形状和类型的1新数组。
empty_like()：返回与给定数组具有相同形状和类型的未初始化的新数组

In [6]:
arr1 = np.zeros((2, 5))
print(arr1)
arr2 = np.empty((2,4))
print(arr2)
arr3 = np.ones_like(arr1)
print(arr3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5.02764148e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


full()：返回给定形状和类型的新数组，用指定的值填充。

full_like()：返回与给定数组具有相同形状和类型的用指定值填充的新数组

In [7]:
arr1 = np.full((2, 3), 6)
arr2 = np.full_like(arr1,5)
print(arr1)
print(arr2)

[[6 6 6]
 [6 6 6]]
[[5 5 5]
 [5 5 5]]


arange()：返回在给定范围内用均匀间隔的值填充的一维数组。

In [8]:
arr1 = np.arange(0, 10, 2)
arr1

array([0, 2, 4, 6, 8])

linspace()：返回指定范围和元素个数的等差数列。数组元素类型为浮点型。

logspace()：返回指定指数范围、元素个数、底数的等比数列。元素类型为浮点型。

以上范围是**左闭右闭**

In [9]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [10]:
np.logspace(1,8,8,base=2)

array([  2.,   4.,   8.,  16.,  32.,  64., 128., 256.])

等差数列的endpoint

以上等差数列的案例可能看着有点懵，核心是np等差数列返回元素的依据是num参数，返回数组包括了end值，因此等差间隔数量是num-1。如果希望等差间隔数量和num一致，返回数组应该是左开右闭即不包含end，此时需要设置endpoint为False（默认是True）

In [11]:
np.linspace(0,10,2, endpoint=False)

array([0., 5.])

生成随机元素数组

- random.rand()：返回给定形状的数组，用 [0,1) 上均匀分布的随机样本填充。
- random.randint()：返回给定形状的数组，用从低位(包含)到高位(不包含)上均匀分布的
随机整数填充。
- random.uniform()：返回给定形状的数组，用从低位(包含)到高位(不包含)上均匀分布
的随机浮点数填充。
- random.randn()：返回给定形状的数组，用标准正态分布(均值为0，标准差为1)的随
机样本填充

In [12]:
np.random.rand(2,3)

array([[0.04833373, 0.03804905, 0.21253496],
       [0.45262157, 0.86531147, 0.61732864]])

In [13]:
np.random.randint(0,100,size=(3,4))

array([[89, 61, 90,  8],
       [93, 82,  3, 60],
       [81, 50, 78, 54]])

In [14]:
np.random.uniform(3, 6, (2, 3))

array([[3.09372571, 5.4008289 , 3.75333431],
       [5.18829994, 3.56610406, 3.99138123]])

In [15]:
np.random.randn(12,18)

array([[-1.97577048e+00,  7.59345296e-01, -1.27258432e-01,
         4.33982136e-01, -5.24692106e-01, -1.00494684e+00,
         1.47844142e-02, -8.58887233e-01, -1.58033238e+00,
        -5.47687574e-01, -2.19788770e-01, -8.15107522e-01,
         1.15424031e+00, -3.69391013e-01, -1.01141911e+00,
        -6.22109679e-01, -1.43536507e-01,  5.06845523e-01],
       [ 9.14292824e-01, -5.41014342e-01,  8.95709292e-02,
        -1.16281394e+00, -1.18240930e+00, -1.84098986e-01,
        -2.46576556e-01, -1.34048155e-01,  1.16521865e+00,
         6.87037380e-01,  6.87589244e-01,  2.11665334e-01,
         9.32009140e-01, -5.62537635e-02,  5.04079157e-01,
        -7.80283080e-02, -8.71549070e-01,  4.72496909e-01],
       [-4.37479335e-02, -3.91760362e-01, -5.62739443e-01,
        -4.19975228e-01,  3.42060752e-01,  3.33518435e-02,
         2.97582826e-01,  6.29055787e-01, -6.32178296e-01,
         5.92819876e-01,  1.34489251e+00,  1.32131406e+00,
         8.07235868e-01,  9.23461269e-01,  9.87915581e

matrix为ndarray的子类，只能生成二维的矩阵

In [16]:
np.matrix('1,2,3; 4,5,6; 7,8,9')

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

创建数组时可以使用dtype参数指定元素类型，也可以使用ndarray.astype()方法转换数组的元素类型

In [17]:
np.array([1,2,3], dtype = np.float32)

array([1., 2., 3.], dtype=float32)

In [18]:
arr = np.array([1,2,3])
arr.astype(dtype = np.float32)

array([1., 2., 3.], dtype=float32)

#### ndarray上的操作

ndarray对索引与切片的支持和list一样，在这里不再赘述

ndarray支持的函数有abs、ceil、floor、rint（四舍五入）、isnan、multiply、divide、where（条件运算符）

In [19]:
arr1 = np.random.randn(2,3)
print(arr1)
print(np.abs(arr1))
print(np.ceil(arr1))
print(np.floor(arr1))
print(np.rint(arr1))
print(np.isnan(arr1))
print(np.multiply(arr1, 2))
print(np.divide(arr1, arr1))
print(np.where(arr1 > 0, 1, 0))

[[-0.30656288 -0.60854873 -0.66682337]
 [ 0.32028317 -1.67448999 -2.09873629]]
[[0.30656288 0.60854873 0.66682337]
 [0.32028317 1.67448999 2.09873629]]
[[-0. -0. -0.]
 [ 1. -1. -2.]]
[[-1. -1. -1.]
 [ 0. -2. -3.]]
[[-0. -1. -1.]
 [ 0. -2. -2.]]
[[False False False]
 [False False False]]
[[-0.61312577 -1.21709746 -1.33364675]
 [ 0.64056635 -3.34897998 -4.19747259]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [1 0 0]]


聚合函数、统计函数

In [20]:
arr1 = np.random.randint(1, 5, (2, 3))
print(arr1)
print(np.mean(arr1))
print(np.sum(arr1))
print(np.max(arr1))
print(np.min(arr1))
print(np.std(arr1)) #标准差
print(np.var(arr1)) #方差
print(np.argmax(arr1)) #最大值的下标索引值
print(np.argmin(arr1))
print(np.cumsum(arr1)) #返回一个一维数组，每个元素都是之前所有元素的累加和
print(np.cumprod(arr1)) #返回一个一维数组，每个元素都是之前所有元素的累计乘积
print(np.cumprod(arr1, axis=1)) #axis：指定沿着哪个轴计算累积乘积。默认为 None，此时会将数组展平后再计算

[[1 4 4]
 [2 2 1]]
2.3333333333333335
14
4
1
1.247219128924647
1.5555555555555556
1
0
[ 1  5  9 11 13 14]
[ 1  4 16 32 64 64]
[[ 1  4 16]
 [ 2  4  4]]


条件函数any、all

In [21]:
arr = np.array([1,2,3])
print(np.all(arr>0))
print(np.any(arr>3))

True
False


ndarray.sort()：就地排序（直接修改原数组）

axis：指定排序的轴。默认值为-1，表示沿着最后一个轴进行排序。所谓的低纬度是嵌套列表的外层。

In [22]:
arr_3d = np.array([[[9, 2, 3],
                    [4, 5, 6]],
                   [[1, 8, 7],
                    [0, 3, 2]]])
print(arr_3d)

[[[9 2 3]
  [4 5 6]]

 [[1 8 7]
  [0 3 2]]]


In [23]:
np.sort(arr_3d)

array([[[2, 3, 9],
        [4, 5, 6]],

       [[1, 7, 8],
        [0, 2, 3]]])

In [24]:
np.sort(arr_3d, axis=-1)

array([[[2, 3, 9],
        [4, 5, 6]],

       [[1, 7, 8],
        [0, 2, 3]]])

In [25]:
np.sort(arr_3d, axis=0)

array([[[1, 2, 3],
        [0, 3, 2]],

       [[9, 8, 7],
        [4, 5, 6]]])

In [26]:
np.sort(arr_3d, axis=1)

array([[[4, 2, 3],
        [9, 5, 6]],

       [[0, 3, 2],
        [1, 8, 7]]])

In [27]:
np.sort(arr_3d, axis=2)

array([[[2, 3, 9],
        [4, 5, 6]],

       [[1, 7, 8],
        [0, 2, 3]]])

In [28]:
print(arr_3d) #这里可以看出内置函数的排序只返回副本
arr_3d.sort() #而ndarray的排序方法是就地排序
print(arr_3d)

[[[9 2 3]
  [4 5 6]]

 [[1 8 7]
  [0 3 2]]]
[[[2 3 9]
  [4 5 6]]

 [[1 7 8]
  [0 2 3]]]


np.unique()：计算唯一值并返回有序结果（一维数组）

In [29]:
arr1 = np.random.randint(0, 5, (3, 3))
print(arr1)
print(np.unique(arr1))

[[1 0 3]
 [1 1 4]
 [4 2 1]]
[0 1 2 3 4]


numpy 中的数组不用编写循环即可执行批量运算，称之为矢量化运算。
大小相等的数组之间的任何算术运算都会将运算应用到元素级

In [30]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(arr1 + arr2)
print(arr1- arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


数组与标量的算术运算会将标量值传播到各个元素

In [31]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1 + 100)
print(arr1- 100)
print(arr1 * 100)
print(arr1 / 100)

[[101 102 103]
 [104 105 106]]
[[-99 -98 -97]
 [-96 -95 -94]]
[[100 200 300]
 [400 500 600]]
[[0.01 0.02 0.03]
 [0.04 0.05 0.06]]


ndarray之间支持运算，前提是shape兼容
- 维度允许不一致，小维度的数组通过在低纬度添加维度的形式对齐维度，如(3)要和(3,4,5)对齐维度，原数组的shape要变为(1,1,3)
- 接下来从高维度到低纬度检查兼容性，如果当前维度大小相同或其中一个大小为1，则互相兼容可以运算，否则不兼容，不能计算
- 维度大小其中一方为1的情形需“扩展”后才能真正兼容，比如[[1]]和[[],[],[]]，前者的大小为1.扩展后为[[1],[1],[1]]。复制的是当前维度的完整元素内容
- 此时两者的shape完全一致，按位置逐个进行运算即可
- 值得注意的是，ndarray的  

In [32]:
arr1 = np.array([1, 2, 3]) 
arr2 = np.array([[4], [5], [6]])
# arr1的shape为(3,)，arr2的shape为(3,1)，为对齐维度，arr1变为[[1,2,3]]
# 从高维到低维度继续处理shape
# 维度2的大小分别为3,1，arr2扩展后变为[[4,4,4],[5,5,5],[6,6,6]]
# 维度1的大小分别为1,3，arr1扩展后变为[[1,2,3],[1,2,3],[1,2,3]]
result = arr1 + arr2
print("规则1示例结果：\n", result)

规则1示例结果：
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


矩阵之间也支持比较运算

In [33]:
a = np.array([1, 5, 3, 8, 2])
b = np.array([2, 5, 1, 8, 3])
print("a > b :", a > b) 

a > b : [False False  True False False]


矩阵乘法运算不是用*或者multiply而是dot方法或内置函数dot、@运算符

In [34]:
import numpy as np

# 设置小参数
batch_size = 2
seq_len = 3
d_model = 4
d_k = 2

# 随机生成输入 X (batch_size, seq_len, d_model)
X = np.random.randint(1, 5, size=(batch_size, seq_len, d_model)).astype(float)
# 权重 W (d_model, d_k)
W = np.random.randint(1, 3, size=(d_model, d_k)).astype(float)

print("X 形状:", X.shape)
print("X:\n", X)
print("W 形状:", W.shape)
print("W:\n", W)

# 批量矩阵乘法
Y = X @ W  # 或者 np.matmul(X, W)
print("Y 形状:", Y.shape)
print("Y:\n", Y)

# 手动验证：用循环计算第一个样本的第一个位置
i, j = 0, 0  # 第一个样本的第一个位置
manual_y = np.dot(X[i, j], W)  # 向量 (d_model,) 乘矩阵 (d_model, d_k) -> (d_k,)
print("手动计算 X[0,0] @ W =", manual_y)
print("Y[0,0] =", Y[0,0])

X 形状: (2, 3, 4)
X:
 [[[2. 2. 3. 3.]
  [3. 2. 2. 4.]
  [4. 3. 1. 3.]]

 [[2. 4. 4. 4.]
  [2. 4. 4. 3.]
  [4. 1. 4. 3.]]]
W 形状: (4, 2)
W:
 [[1. 1.]
 [2. 2.]
 [1. 1.]
 [1. 2.]]
Y 形状: (2, 3, 2)
Y:
 [[[12. 15.]
  [13. 17.]
  [14. 17.]]

 [[18. 22.]
  [17. 20.]
  [13. 16.]]]
手动计算 X[0,0] @ W = [12. 15.]
Y[0,0] = [12. 15.]
